-- MM2 item values from mm2values.com. Auto-built 2026-10-02, do not edit by hand.
-- byKey keys: 'rarity|type|name', byTB: 'type|name' (fallback). v = value, d = demand.
return {
byKey = {
["ancient|gun|gingerscope"]={v=16000,d=5,name="Gingerscope"},
["ancient|gun|harvester"]={v=250,d=3,name="Harvester"},
["ancient|gun|icepiercer"]={v=165,d=2.5,name="Icepiercer"},
["ancient|knife|batwing"]={v=45,d=2,name="Batwing"},
["ancient|knife|celestial"]={v=2250,d=5,name="Celestial"},
["ancient|knife|elderwoodscythe"]={v=40,d=2,name="Elderwood Scythe"},
["ancient|knife|hallowscythe"]={v=32,d=2,name="Hallowscythe"},
["ancient|knife|icebreaker"]={v=70,d=2,name="Icebreaker"},
["ancient|knife|icewing"]={v=15,d=2,name="Ice Wing"},
["ancient|knife|logchopper"]={v=20,d=1.5,name="Log Chopper"},
["ancient|knife|niksscythe"]={v=250000000,d=11,name="Niks Scythe"},
["ancient|knife|swirlyaxe"]={v=40,d=2,name="SwirlyAxe"},
["ancient|knife|travelersaxe"]={v=8000,d=5,name="Travelers Axe"},
["ancient|knife|vampiresaxe"]={v=1650,d=5,name="Vampires Axe"},
["chroma|gun|chromabauble"]={v=32000,d=6,name="Chroma Bauble"},
["chroma|gun|chromaconstellation"]={v=30000,d=6,name="Chroma Constellation"},
["chroma|gun|chromadarkbringer"]={v=60,d=2,name="Chroma Darkbringer"},
["chroma|gun|chromaever"]={v=56000,d=6,name="Chroma Evergun"},
["chroma|gun|chromalaser"]={v=40,d=2,name="Chroma Laser"},
["chroma|gun|chromalightbringer"]={v=55,d=2,name="Chroma Lightbringer"},
["chroma|gun|chromaluger"]={v=48,d=2,name="Chroma Luger"},
["chroma|gun|chromaray"]={v=14000,d=5,name="Chroma Raygun"},
["chroma|gun|chromashark"]={v=33,d=1.5,name="Chroma Shark"},
["chroma|gun|chromasunrise"]={v=10500,d=5,name="Chroma Sunrise"},
["chroma|gun|chromaswirly"]={v=35,d=1,name="Chroma Swirlygun"},
["chroma|gun|chromatravelers"]={v=145000,d=7,name="Chroma Travelers Gun"},
["chroma|gun|chromatreat"]={v=1800,d=4.5,name="Chroma Treat"},
["chroma|gun|chromawater"]={v=2550,d=4,name="Chroma WaterGun"},
["chroma|knife|chromaalienbeam"]={v=23000,d=6,name="Chroma Alienbeam"},
["chroma|knife|chromaboneblade"]={v=20,d=1,name="Chroma Boneblade"},
["chroma|knife|chromacandleflame"]={v=40,d=1,name="Chroma Candleflame"},
["chroma|knife|chromacookiecane"]={v=30,d=1,name="Chroma Cookiecane"},
["chroma|knife|chromadeathshard"]={v=35,d=1,name="Chroma DeathShard"},
["chroma|knife|chromaelderwoodblade"]={v=35,d=1,name="Chroma Elderwood Blade"},
["chroma|knife|chromaevergreen"]={v=41000,d=6,name="Chroma Evergreen"},
["chroma|knife|chromafang"]={v=33,d=1,name="Chroma Fang"},
["chroma|knife|chromagemstone"]={v=33,d=1,name="Chroma Gemstone"},
["chroma|knife|chromagingerblade"]={v=25,d=1,name="Chroma Gingerblade"},
["chroma|knife|chromaheartwand"]={v=4000,d=4.5,name="Chroma Heart Wand"},
["chroma|knife|chromaheat"]={v=30,d=1,name="Chroma Heat"},
["chroma|knife|chromasaw"]={v=22,d=1,name="Chroma Saw"},
["chroma|knife|chromaseer"]={v=25,d=1,name="Chroma Seer"},
["chroma|knife|chromaslasher"]={v=33,d=2,name="Chroma Slasher"},
["chroma|knife|chromasunset"]={v=7750,d=6,name="Chroma Sunset"},
["chroma|knife|chromasweet"]={v=1750,d=4.5,name="Chroma Sweet"},
["chroma|knife|chromatides"]={v=25,d=1,name="Chroma Tides"},
["common|gun|apocalypse"]={v=2,d=2,name="Apocalypse Gun"},
["common|gun|balloons"]={v=1,d=0,name="Balloons Gun"},
["common|gun|bats"]={v=2,d=0,name="Bats"},
["common|gun|bigkill"]={v=1,d=0,name="Big Kill"},
["common|gun|bit"]={v=1,d=0,name="Bit"},
["common|gun|candied"]={v=2,d=0,name="Candied Gun 2022"},
["common|gun|candycorn"]={v=3,d=3,name="Candycorn Gun"},
["common|gun|carved"]={v=3,d=0,name="Carved (Gun)"},
["common|gun|clownfish"]={v=1,d=0,name="Clownfish Gun"},
["common|gun|coal"]={v=1,d=2,name="Coal Gun 2022"},
["common|gun|cold"]={v=1,d=0,name="Cold"},
["common|gun|darkness"]={v=3,d=0,name="Darkness Gun"},
["common|gun|elf"]={v=3,d=1,name="Elf (Gun)"},
["common|gun|engraved"]={v=1,d=0,name="Engraved"},
["common|gun|fall"]={v=1,d=3,name="Fall"},
["common|gun|fallout"]={v=1,d=0,name="Fallout"},
["common|gun|fragile"]={v=2,d=0,name="Fragile Gun"},
["common|gun|frozen"]={v=2,d=0,name="Frozen Gun 23"},
["common|gun|hl2"]={v=1,d=0,name="HL2"},
["common|gun|igloo"]={v=3,d=0,name="Igloo Gun"},
["common|gun|infected"]={v=3,d=2,name="Infected Gun"},
["common|gun|infiltrator"]={v=1,d=0,name="Infiltrator"},
["common|gun|iron"]={v=1,d=0,name="Iron"},
["common|gun|juice"]={v=1,d=0,name="Juice"},
["common|gun|news"]={v=1,d=0,name="News"},
["common|gun|pea"]={v=1,d=0,name="Pea"},
["common|gun|plaid"]={v=0,d=0,name="Plaid Gun"},
["common|gun|sandy"]={v=1,d=0,name="Sandy Gun"},
["common|gun|santa"]={v=2,d=0,name="Santa Gun 23"},
["common|gun|snowman"]={v=1,d=2,name="Snowman Gun 2022"},
["common|gun|star"]={v=1,d=0,name="Star"},
["common|gun|starfish"]={v=1,d=0,name="Starfish Gun"},
["common|gun|starry"]={v=4,d=2,name="Starry"},
["common|gun|sticker"]={v=2,d=0,name="Sticker Gun"},
["common|gun|stickers"]={v=3,d=0,name="Stickers Knife"},
["common|gun|stickersxmas"]={v=2,d=1,name="Stickers Xmas 24"},
["common|gun|stockings"]={v=2,d=0,name="Stockings Gun 24"},
["common|gun|strawberries"]={v=4,d=2,name="Strawberries Gun"},
["common|gun|striped"]={v=2,d=1.5,name="Striped Gun"},
["common|gun|toy"]={v=3,d=0,name="Toy Gun"},
["common|gun|ufos"]={v=1,d=3,name="UFOs Gun"},
["common|gun|watcher"]={v=3,d=0,name="Watcher gun 2020"},
["common|gun|wavy"]={v=3,d=0,name="Wavy Gun"},
["common|gun|webs"]={v=1,d=2,name="Webs Gun"},
["common|knife|8bit"]={v=1,d=0,name="8Bit"},
["common|knife|apocalypse"]={v=1,d=2,name="Apocalypse Knife"},
["common|knife|aqua"]={v=1,d=0,name="Aqua"},
["common|knife|bats"]={v=3,d=2,name="Bats"},
["common|knife|bells"]={v=2,d=0,name="Bells"},
["common|knife|bleached"]={v=1,d=0,name="Bleached"},
["common|knife|borders"]={v=1,d=0,name="Borders"},
["common|knife|candied"]={v=1,d=2,name="Candied Knife"},
["common|knife|candle"]={v=2,d=0,name="Candle"},
["common|knife|candles"]={v=2,d=0,name="Candles"},
["common|knife|candycorn"]={v=12,d=2,name="Candycorn 2019"},
["common|knife|cardboard"]={v=1,d=0,name="Cardboard"},
["common|knife|carrots"]={v=1,d=0,name="Carrots"},
["common|knife|carved"]={v=3,d=0,name="Carved (Knife)"},
["common|knife|cats"]={v=3,d=3,name="Cats"},
["common|knife|cherry"]={v=1,d=0,name="Cherry"},
["common|knife|chick"]={v=1,d=0,name="Chick"},
["common|knife|clan"]={v=1,d=0,name="Clan"},
["common|knife|clown"]={v=1,d=0,name="Clown"},
["common|knife|clownfish"]={v=1,d=0,name="Clownfish Knife"},
["common|knife|coal"]={v=2,d=0,name="Coal Knife 2022"},
["common|knife|coconut"]={v=1,d=1.5,name="Coconut Knife"},
["common|knife|combatii"]={v=11,d=2,name="Combat II"},
["common|knife|darkness"]={v=1,d=2,name="Darkness Knife"},
["common|knife|dolphins"]={v=1,d=1.5,name="Dolphins Knife"},
["common|knife|eco"]={v=1,d=0,name="Eco"},
["common|knife|elf"]={v=1,d=2,name="Elf (2017)"},
["common|knife|eyeball"]={v=3,d=0,name="Eyeball Knife"},
["common|knife|fragile"]={v=2,d=0,name="Fragile Knife"},
["common|knife|frozen"]={v=2,d=0,name="Frozen Knife 23"},
["common|knife|ghosts"]={v=2,d=0,name="Ghosts"},
["common|knife|giftbag"]={v=3,d=2,name="Gift Bag Knife"},
["common|knife|gifts"]={v=3,d=0,name="Gifts 2024"},
["common|knife|glitch1"]={v=60,d=2.5,name="Glitch 1"},
["common|knife|glitch2"]={v=30,d=1,name="Glitch 2"},
["common|knife|haunted"]={v=3,d=3,name="Haunted"},
["common|knife|hearts"]={v=4,d=2,name="Hearts Knife"},
["common|knife|hotchocolate"]={v=3,d=0,name="Hot Chocolate"},
["common|knife|hunter"]={v=1,d=2,name="Hunter Knife"},
["common|knife|ice"]={v=1,d=0,name="Ice"},
["common|knife|igloo"]={v=2,d=0,name="Igloo Knife"},
["common|knife|infected"]={v=1,d=2,name="Infected Knife"},
["common|knife|leaves"]={v=1,d=1.5,name="Leaves Knife"},
["common|knife|linked"]={v=1,d=0,name="Linked"},
["common|knife|log"]={v=1,d=0,name="Log"},
["common|knife|love"]={v=1,d=2,name="Love"},
["common|knife|oily"]={v=1,d=0,name="Oily"},
["common|knife|ollie"]={v=8,d=2,name="Ollie"},
["common|knife|ornament1"]={v=1,d=1,name="Ornament 1"},
["common|knife|passion"]={v=1,d=2,name="Passion"},
["common|knife|present"]={v=2,d=0,name="Present Knife"},
["common|knife|rb"]={v=1,d=2,name="RB Knife"},
["common|knife|reindeer"]={v=2,d=0,name="Reindeer 2024"},
["common|knife|ribbon"]={v=2,d=0,name="Ribbon Knife"},
["common|knife|roses"]={v=1,d=2,name="Roses"},
["common|knife|sandy"]={v=1,d=0,name="Sandy"},
["common|knife|scarf"]={v=1,d=2,name="Scarf"},
["common|knife|skyline"]={v=1,d=0,name="Skyline Knife"},
["common|knife|slashed"]={v=1,d=2,name="Slashed"},
["common|knife|slate"]={v=1,d=0,name="Slate"},
["common|knife|slime"]={v=3,d=0.5,name="Slime Knife"},
["common|knife|snowfall"]={v=2,d=0,name="Snowfall"},
["common|knife|snowman"]={v=2,d=0,name="Snowman Knife 2022"},
["common|knife|sparkle9"]={v=30,d=2,name="Sparkle9"},
["common|knife|spider"]={v=1,d=0,name="Spider"},
["common|knife|splatter"]={v=1,d=0,name="Splatter"},
["common|knife|stainless"]={v=1,d=0,name="Stainless"},
["common|knife|starfish"]={v=1,d=0,name="Starfish Knife"},
["common|knife|static"]={v=1,d=0,name="Static"},
["common|knife|stickers"]={v=3,d=0,name="Stickers Knife"},
["common|knife|stickersxmas"]={v=3,d=0,name="Stickers Xmas 2024"},
["common|knife|stockings"]={v=1,d=0,name="Stockings"},
["common|knife|strawberries"]={v=4,d=2,name="Strawberries Knife"},
["common|knife|striped"]={v=1,d=1.5,name="Striped Knife"},
["common|knife|sweetheart"]={v=1,d=2,name="Sweetheart"},
["common|knife|tnl"]={v=2,d=1,name="TNL"},
["common|knife|toy"]={v=2,d=2,name="Toy Knife"},
["common|knife|ufos"]={v=3,d=3,name="UFOs Knife"},
["common|knife|valentine"]={v=1,d=2,name="Valentine"},
["common|knife|vines"]={v=2,d=2,name="Vines Knife"},
["common|knife|watcher"]={v=2,d=0,name="Watcher Knife 2020"},
["common|knife|wavy"]={v=3,d=0,name="Wavy Knife"},
["common|knife|whiteout"]={v=1,d=0,name="Whiteout"},
["common|knife|witch"]={v=1,d=1,name="Witch"},
["common|knife|wood"]={v=1,d=0,name="Wood Knife"},
["godly|gun|amerilaser"]={v=23,d=2,name="Amerilaser"},
["godly|gun|bauble"]={v=675,d=4,name="Bauble"},
["godly|gun|blaster"]={v=17,d=1.5,name="Blaster"},
["godly|gun|blossom"]={v=1380,d=5,name="Blossom"},
["godly|gun|borealis"]={v=140,d=2.5,name="Borealis"},
["godly|gun|constellation"]={v=2725,d=5,name="Constellation"},
["godly|gun|darkbringer"]={v=35,d=2,name="Darkbringer"},
["godly|gun|elderwoodrevolver"]={v=35,d=2,name="Elderwood Revolver"},
["godly|gun|ever"]={v=3425,d=5,name="Evergun"},
["godly|gun|flora"]={v=410,d=4.5,name="Flora"},
["godly|gun|flowerwood"]={v=260,d=4,name="Flowerwood Gun"},
["godly|gun|gingermint"]={v=14,d=1,name="Gingermint"},
["godly|gun|greenluger"]={v=25,d=2,name="Green Luger"},
["godly|gun|hallow"]={v=22,d=2,name="Hallowgun"},
["godly|gun|icebeam"]={v=20,d=1.5,name="Icebeam"},
["godly|gun|iceblaster"]={v=35,d=2,name="Iceblaster"},
["godly|gun|jingle"]={v=15,d=2,name="Jinglegun"},
["godly|gun|laser"]={v=23,d=2,name="Laser"},
["godly|gun|lightbringer"]={v=33,d=2,name="Lightbringer"},
["godly|gun|luger"]={v=17,d=1,name="Luger"},
["godly|gun|lugercane"]={v=15,d=2,name="Luger Cane"},
["godly|gun|makeshift"]={v=33,d=1,name="Makeshift"},
["godly|gun|minty"]={v=15,d=1,name="Minty"},
["godly|gun|ocean"]={v=280,d=4,name="Ocean"},
["godly|gun|pearlshine"]={v=80,d=2,name="Pearlshine"},
["godly|gun|plasmabeam"]={v=20,d=1.5,name="Plasmabeam"},
["godly|gun|rainbow"]={v=430,d=5,name="Rainbow Gun"},
["godly|gun|ray"]={v=1875,d=5,name="Raygun"},
["godly|gun|redluger"]={v=38,d=2,name="Red Luger"},
["godly|gun|shark"]={v=20,d=2,name="Shark"},
["godly|gun|soul"]={v=650,d=5,name="Soul"},
["godly|gun|spectre"]={v=37,d=1,name="Spectre"},
["godly|gun|sugar"]={v=33,d=1.5,name="Sugar"},
["godly|gun|sunset"]={v=675,d=4,name="Sunset"},
["godly|gun|swirly"]={v=18,d=1,name="Swirlygun"},
["godly|gun|travelers"]={v=5150,d=5,name="Travelers Gun"},
["godly|gun|treat"]={v=155,d=2.5,name="Treat"},
["godly|gun|vampires"]={v=1875,d=5,name="Vampires Gun"},
["godly|gun|water"]={v=160,d=2,name="WaterGun"},
["godly|gun|xenoshot"]={v=420,d=4.5,name="Xenoshot"},
["godly|knife|alienbeam"]={v=2000,d=5,name="Alienbeam"},
["godly|knife|australis"]={v=135,d=2.5,name="Australis"},
["godly|knife|bat"]={v=120,d=2,name="Bat"},
["godly|knife|battleaxe"]={v=13,d=1,name="BattleAxe"},
["godly|knife|bioblade"]={v=10,d=1,name="Bioblade"},
["godly|knife|bloom"]={v=400,d=4.5,name="Bloom"},
["godly|knife|blueseer"]={v=3,d=1,name="Blue Seer"},
["godly|knife|boneblade"]={v=8,d=1,name="Boneblade"},
["godly|knife|candleflame"]={v=35,d=2,name="Candleflame"},
["godly|knife|candy"]={v=90,d=2,name="Candy"},
["godly|knife|chill"]={v=12,d=1,name="Chill"},
["godly|knife|clockwork"]={v=12,d=1,name="Clockwork"},
["godly|knife|cookieblade"]={v=4,d=1,name="Cookieblade"},
["godly|knife|cookiecane"]={v=14,d=1,name="Cookiecane"},
["godly|knife|deathshard"]={v=13,d=1,name="Death Shard"},
["godly|knife|eggblade"]={v=5,d=1,name="Eggblade"},
["godly|knife|elderwoodblade"]={v=32,d=1,name="Elderwood Blade"},
["godly|knife|eternal"]={v=10,d=1,name="Eternal"},
["godly|knife|eternalcane"]={v=13,d=1.5,name="Eternal Cane"},
["godly|knife|eternalii"]={v=8,d=1,name="Eternal II"},
["godly|knife|eternaliii"]={v=10,d=1,name="Eternal III"},
["godly|knife|eternaliv"]={v=10,d=1,name="Eternal IV"},
["godly|knife|evergreen"]={v=2550,d=5,name="Evergreen"},
["godly|knife|fang"]={v=12,d=1,name="Fang"},
["godly|knife|flames"]={v=7,d=1,name="Flames"},
["godly|knife|flowerwood"]={v=255,d=4,name="Flowerwood Knife"},
["godly|knife|frostbite"]={v=7,d=1,name="Frostbite"},
["godly|knife|frostsaber"]={v=10,d=1,name="Frostsaber"},
["godly|knife|gemstone"]={v=13,d=1,name="Gemstone"},
["godly|knife|ghostblade"]={v=8,d=1,name="Ghost Blade"},
["godly|knife|gingerblade"]={v=13,d=1,name="Gingerblade"},
["godly|knife|hallowsblade"]={v=7,d=1,name="Hallows Blade"},
["godly|knife|hallowsedge"]={v=9,d=1,name="Hallows Edge"},
["godly|knife|handsaw"]={v=9,d=1,name="Handsaw"},
["godly|knife|heartblade"]={v=65,d=2,name="Heartblade"},
["godly|knife|heartwand"]={v=350,d=4.5,name="Heart Wand"},
["godly|knife|heat"]={v=12,d=1,name="Heat"},
["godly|knife|icedragon"]={v=7,d=1,name="Ice Dragon"},
["godly|knife|iceflake"]={v=18,d=1.5,name="Iceflake"},
["godly|knife|iceshard"]={v=9,d=1,name="Ice Shard"},
["godly|knife|nebula"]={v=13,d=1,name="Nebula"},
["godly|knife|nightblade"]={v=20,d=1.5,name="Night Blade"},
["godly|knife|oldglory"]={v=17,d=1.5,name="Old Glory"},
["godly|knife|orangeseer"]={v=2,d=1,name="Orange Seer"},
["godly|knife|pearl"]={v=75,d=2,name="Pearl"},
["godly|knife|phantom"]={v=37,d=1,name="Phantom"},
["godly|knife|pixel"]={v=18,d=1.5,name="Pixel"},
["godly|knife|plasmablade"]={v=17,d=1,name="Plasmablade"},
["godly|knife|prismatic"]={v=5,d=1,name="Prismatic"},
["godly|knife|pumpking"]={v=8,d=1,name="Pumpking"},
["godly|knife|purpleseer"]={v=3,d=1,name="Purple Seer"},
["godly|knife|rainbow"]={v=430,d=5,name="Rainbow Gun"},
["godly|knife|redseer"]={v=3,d=1,name="Red Seer"},
["godly|knife|sakura"]={v=1360,d=5,name="Sakura"},
["godly|knife|saw"]={v=8,d=1,name="Saw"},
["godly|knife|seer"]={v=3,d=1,name="Seer"},
["godly|knife|slasher"]={v=15,d=1,name="Slasher"},
["godly|knife|snowflake"]={v=5,d=1,name="Snowflake"},
["godly|knife|spider"]={v=12,d=1,name="Spider"},
["godly|knife|spirit"]={v=640,d=5,name="Spirit"},
["godly|knife|sunrise"]={v=1100,d=4,name="Sunrise"},
["godly|knife|sweet"]={v=150,d=2.5,name="Sweet"},
["godly|knife|swirlyblade"]={v=13,d=1,name="Swirlyblade"},
["godly|knife|tides"]={v=12,d=1,name="Tides"},
["godly|knife|turkey"]={v=2000,d=5,name="Turkey"},
["godly|knife|vampiresedge"]={v=15,d=1,name="Vampires Edge"},
["godly|knife|virtual"]={v=15,d=1,name="Virtual"},
["godly|knife|waves"]={v=275,d=4,name="Waves"},
["godly|knife|wintersedge"]={v=7,d=1,name="Winters Edge"},
["godly|knife|xeno"]={v=410,d=4.5,name="Xenoknife"},
["godly|knife|xmas"]={v=10,d=1,name="Xmas"},
["godly|knife|yellowseer"]={v=2,d=1,name="Yellow Seer"},
["legend|gun|aquarium"]={v=2,d=1,name="Aquarium Gun"},
["legend|gun|arctic"]={v=12,d=1.5,name="Arctic Gun"},
["legend|gun|aurora"]={v=40,d=2,name="Aurora Gun"},
["legend|gun|cavern"]={v=1,d=1,name="Cavern Gun"},
["legend|gun|chromatic"]={v=3,d=2,name="Chromatic Gun"},
["legend|gun|cursed"]={v=1,d=1,name="Cursed"},
["legend|gun|energized"]={v=2,d=2,name="Energized Gun"},
["legend|gun|frostfade"]={v=3,d=2,name="Frostfade Gun"},
["legend|gun|ghost"]={v=1,d=1,name="Ghost Gun"},
["legend|gun|ginger"]={v=5,d=1,name="Ginger Gun"},
["legend|gun|latte"]={v=145,d=2,name="Latte Gun"},
["legend|gun|nightsky"]={v=1,d=1.5,name="Nightsky"},
["legend|gun|overseer"]={v=4,d=2.5,name="Overseer (gun)"},
["legend|gun|palms"]={v=2,d=2,name="Palms Gun"},
["legend|gun|predator"]={v=4,d=3,name="Predator (gun)"},
["legend|gun|ripper"]={v=3,d=2,name="Ripper Gun"},
["legend|gun|rupture"]={v=1,d=1,name="Rupture"},
["legend|gun|sparkle"]={v=3,d=2,name="Sparkle"},
["legend|gun|spectral"]={v=4,d=2.5,name="Spectral Gun"},
["legend|gun|splash"]={v=3,d=1,name="Splash Gun"},
["legend|gun|traveler"]={v=45,d=2,name="Traveler Gun"},
["legend|gun|tree"]={v=1,d=1,name="Tree (gun)"},
["legend|gun|universe"]={v=3,d=2,name="Universe"},
["legend|gun|vampire"]={v=40,d=2,name="Vampire Gun"},
["legend|gun|viper"]={v=3,d=2,name="Viper"},
["legend|knife|aquarium"]={v=2,d=1,name="Aquarium Knife"},
["legend|knife|arctic"]={v=3,d=3,name="Arctic Knife"},
["legend|knife|aurora"]={v=3,d=2.5,name="Aurora Knife"},
["legend|knife|beach"]={v=35,d=2,name="Beach"},
["legend|knife|blueelite"]={v=4,d=1,name="Blue Elite"},
["legend|knife|bluescratch"]={v=3,d=1,name="Blue Scratch"},
["legend|knife|broken"]={v=7,d=2,name="Broken"},
["legend|knife|bunnies"]={v=4,d=2,name="Bunnies"},
["legend|knife|cavern"]={v=8,d=1.5,name="Cavern Knife"},
["legend|knife|chromatic"]={v=4,d=2,name="Chromatic Knife"},
["legend|knife|cottoncandy"]={v=40,d=2,name="Cotton Candy"},
["legend|knife|cupid"]={v=1,d=3,name="Cupid"},
["legend|knife|cursed"]={v=1,d=1,name="Cursed"},
["legend|knife|elite"]={v=3,d=1,name="Elite"},
["legend|knife|emerald"]={v=4,d=2,name="Emerald"},
["legend|knife|energized"]={v=1,d=2,name="Energized Knife"},
["legend|knife|fade"]={v=3,d=2,name="Fade"},
["legend|knife|frostfade"]={v=2,d=1.5,name="Frostfade Knife"},
["legend|knife|fusion"]={v=3,d=2,name="Fusion"},
["legend|knife|ghost"]={v=5,d=1,name="Ghost Knife"},
["legend|knife|ginger"]={v=2,d=2,name="Ginger Knife"},
["legend|knife|greenelite"]={v=4,d=1,name="Green Elite"},
["legend|knife|greenfire"]={v=3,d=1,name="Green Fire"},
["legend|knife|icecracker"]={v=2,d=1,name="Icecracker"},
["legend|knife|icedriller"]={v=6,d=1,name="Icedriller"},
["legend|knife|jd"]={v=30,d=2,name="JD"},
["legend|knife|latte"]={v=145,d=2,name="Latte Knife"},
["legend|knife|midnight"]={v=3,d=2,name="Midnight"},
["legend|knife|nightstar"]={v=2,d=2,name="Nightstar"},
["legend|knife|overseer"]={v=4,d=3,name="Overseer (knife)"},
["legend|knife|palms"]={v=2,d=1,name="Palms Knife"},
["legend|knife|plasmite"]={v=3,d=2,name="Plasmite"},
["legend|knife|predator"]={v=4,d=2.5,name="Predator (knife)"},
["legend|knife|redfire"]={v=2,d=1,name="Red Fire"},
["legend|knife|ripper"]={v=4,d=2,name="Ripper Knife"},
["legend|knife|rune"]={v=3,d=2,name="Rune"},
["legend|knife|santasmagic"]={v=5,d=1,name="Santas Magic"},
["legend|knife|santasspirit"]={v=5,d=1,name="Santas Spirit"},
["legend|knife|scratch"]={v=4,d=1,name="Scratch"},
["legend|knife|shiny"]={v=3,d=2,name="Shiny"},
["legend|knife|skulls"]={v=3,d=1.5,name="Skulls"},
["legend|knife|spectral"]={v=45,d=2,name="Spectral Knife"},
["legend|knife|splash"]={v=3,d=2,name="Splash"},
["legend|knife|traveler"]={v=2,d=2.5,name="Traveler Knife"},
["legend|knife|tree"]={v=1,d=1,name="Tree (knife)"},
["legend|knife|vampire"]={v=2,d=2,name="Vampire Knife"},
["legend|knife|web"]={v=1,d=1,name="Web"},
["legend|knife|witched"]={v=5,d=1.5,name="Witched"},
["rare|gun|ace"]={v=3,d=2,name="Ace"},
["rare|gun|aurora"]={v=2,d=2,name="Aurora Gun"},
["rare|gun|bacon"]={v=3,d=2,name="Bacon"},
["rare|gun|butterflies"]={v=3,d=1,name="Butterflies"},
["rare|gun|candleflame"]={v=4,d=2,name="Candleflame"},
["rare|gun|candyswirl"]={v=2,d=1,name="Candy Swirl Gun"},
["rare|gun|cane"]={v=2,d=2,name="Cane Gun"},
["rare|gun|floral"]={v=2,d=1,name="Floral Gun"},
["rare|gun|frostflame"]={v=1,d=2,name="Frostflame Gun"},
["rare|gun|galactic"]={v=3,d=2,name="Galactic"},
["rare|gun|ghastly"]={v=12,d=2,name="Ghastly Gun"},
["rare|gun|ghostfire"]={v=15,d=2,name="Ghostfire"},
["rare|gun|ghosts"]={v=2,d=2,name="Ghosts"},
["rare|gun|ginger"]={v=3,d=1,name="Ginger (Gun)"},
["rare|gun|gingerbread"]={v=3,d=2,name="Gingerbread Gun 2022"},
["rare|gun|hacker"]={v=3,d=2,name="Hacker"},
["rare|gun|heartbreak"]={v=3,d=2,name="Heartbreak"},
["rare|gun|hologram"]={v=3,d=2,name="Hologram Gun"},
["rare|gun|icicles"]={v=3,d=1,name="Icicles Gun"},
["rare|gun|imbued"]={v=3,d=2,name="Imbued"},
["rare|gun|irevolver"]={v=3,d=2,name="iRevolver"},
["rare|gun|magma"]={v=10,d=2,name="Magma Gun"},
["rare|gun|molten"]={v=2,d=2,name="Molten (Gun)"},
["rare|gun|monster"]={v=4,d=1,name="Monster"},
["rare|gun|mummy"]={v=3,d=1,name="Mummy"},
["rare|gun|neon"]={v=3,d=2,name="Neon Gun"},
["rare|gun|nightfire"]={v=3,d=2,name="Nightfire"},
["rare|gun|nuclear"]={v=2,d=2.5,name="Nuclear"},
["rare|gun|popart"]={v=2,d=2,name="Pop Art Gun"},
["rare|gun|ritual"]={v=1,d=1,name="Ritual"},
["rare|gun|silentnight"]={v=15,d=1.5,name="Silent Night Gun"},
["rare|gun|snakebite"]={v=1,d=1,name="Snakebite Gun"},
["rare|gun|snowflake"]={v=2,d=2,name="Snowflake Gun 23"},
["rare|gun|starry"]={v=20,d=2,name="Starry Gun"},
["rare|gun|sunny"]={v=1,d=1,name="Sunny"},
["rare|gun|sunset"]={v=1,d=2,name="Sunset"},
["rare|gun|toxic"]={v=2,d=1,name="Toxic Gun"},
["rare|gun|tree"]={v=3,d=2,name="Tree Gun 2022"},
["rare|gun|vampire"]={v=10,d=1,name="Vampire Gun"},
["rare|gun|watcher"]={v=20,d=3,name="Watcher Gun"},
["rare|gun|wraith"]={v=2,d=2,name="Wraith Gun"},
["rare|gun|xeno"]={v=3,d=3,name="Xeno Gun"},
["rare|knife|abstract"]={v=3,d=2,name="Abstract"},
["rare|knife|aurora"]={v=7,d=1.5,name="Aurora Knife"},
["rare|knife|biogel"]={v=3,d=2,name="Biogel"},
["rare|knife|bones"]={v=2,d=2,name="Bones"},
["rare|knife|candyswirl"]={v=1,d=2,name="Candy Swirl Knife"},
["rare|knife|cane"]={v=525,d=4,name="Cane Knife"},
["rare|knife|curse"]={v=2,d=2,name="Curse Knife"},
["rare|knife|damp"]={v=3,d=2,name="Damp"},
["rare|knife|dark"]={v=65,d=3,name="DarkKnife"},
["rare|knife|deepsea"]={v=3,d=2,name="Deep Sea"},
["rare|knife|dungeon"]={v=135,d=2.5,name="Dungeon"},
["rare|knife|floral"]={v=12,d=2,name="Floral"},
["rare|knife|frostflame"]={v=3,d=2,name="Frostflame Knife"},
["rare|knife|galaxy"]={v=3,d=2,name="Galaxy"},
["rare|knife|ginger"]={v=3,d=1,name="Ginger (Knife)"},
["rare|knife|gingerbread"]={v=2,d=2,name="GingerBread"},
["rare|knife|greenmarble"]={v=3,d=1,name="Green Marble"},
["rare|knife|heart"]={v=1,d=2,name="Heart"},
["rare|knife|hologram"]={v=3,d=3,name="Hologram Knife"},
["rare|knife|icicles"]={v=1,d=2,name="Icicles Knife"},
["rare|knife|jack"]={v=3,d=1.5,name="Jack"},
["rare|knife|korblox"]={v=3,d=2,name="Korblox"},
["rare|knife|kraken"]={v=1,d=1,name="Kraken"},
["rare|knife|krypto"]={v=3,d=2,name="Krypto"},
["rare|knife|logcutter"]={v=3,d=2,name="Logcutter"},
["rare|knife|magma"]={v=7,d=1.5,name="Magma"},
["rare|knife|makeshift"]={v=40,d=3,name="Makeshift Knife"},
["rare|knife|molten"]={v=2,d=2,name="Molten (Knife)"},
["rare|knife|musical"]={v=3,d=2,name="Musical"},
["rare|knife|nether"]={v=3,d=2,name="Nether"},
["rare|knife|nova"]={v=3,d=2,name="Nova"},
["rare|knife|orangemarble"]={v=2,d=1,name="Orange Marble"},
["rare|knife|painted"]={v=1,d=2,name="Painted Knife"},
["rare|knife|popart"]={v=2,d=2,name="Pop Art Knife"},
["rare|knife|portal"]={v=3,d=2,name="Portal Knife"},
["rare|knife|rainbow"]={v=3,d=2,name="Rainbow"},
["rare|knife|robot"]={v=2,d=2,name="Robot Knife"},
["rare|knife|sharkie"]={v=1,d=2,name="Sharkie Knife"},
["rare|knife|silentnight"]={v=50,d=1.5,name="Silent Night Knife"},
["rare|knife|sleigh"]={v=1,d=2,name="Sleigh"},
["rare|knife|snakebite"]={v=3,d=1,name="Snakebite Knife"},
["rare|knife|snowflakes"]={v=15,d=2,name="Snowflakes"},
["rare|knife|snowglobe"]={v=2,d=2,name="Snowglobe Knife"},
["rare|knife|snowy"]={v=1,d=2,name="Snowy"},
["rare|knife|space"]={v=3,d=2,name="Space"},
["rare|knife|spectrum"]={v=3,d=2,name="Spectrum"},
["rare|knife|spring"]={v=2,d=2,name="Spring Knife"},
["rare|knife|squire"]={v=3,d=2,name="Squire"},
["rare|knife|starry"]={v=2,d=2,name="Starry Knife"},
["rare|knife|storm"]={v=2,d=1,name="Storm"},
["rare|knife|swirl"]={v=17,d=2,name="Swirl Knife"},
["rare|knife|toxic"]={v=8,d=1.5,name="Toxic Knife"},
["rare|knife|tree"]={v=3,d=2,name="Tree Knife 23"},
["rare|knife|tropical"]={v=3,d=2,name="Tropical Knife"},
["rare|knife|vortex"]={v=3,d=2,name="Vortex"},
["rare|knife|watcher"]={v=3,d=2,name="Watcher Knife"},
["rare|knife|waves"]={v=2,d=1,name="Waves Knife"},
["rare|knife|wraith"]={v=2,d=2,name="Wraith Knife"},
["rare|knife|xeno"]={v=1,d=4,name="Xeno Knife"},
["rare|knife|yummy"]={v=3,d=2,name="Yummy Knife"},
["rare|knife|zombified"]={v=30,d=3,name="Zombified"},
["uncommon|gun|adurite"]={v=3,d=0,name="Adurite (Gun)"},
["uncommon|gun|bluesteel"]={v=3,d=0,name="Bluesteel (Gun)"},
["uncommon|gun|bones"]={v=180,d=2.5,name="Bones Gun"},
["uncommon|gun|brains"]={v=2,d=2,name="Brains Gun"},
["uncommon|gun|camo"]={v=3,d=0,name="Camo"},
["uncommon|gun|canes"]={v=1,d=2,name="Canes Gun"},
["uncommon|gun|carrot"]={v=2,d=2,name="Carrot Gun"},
["uncommon|gun|caution"]={v=3,d=0,name="Caution"},
["uncommon|gun|cheddar"]={v=3,d=0,name="Cheddar"},
["uncommon|gun|clown"]={v=3,d=1,name="Clown"},
["uncommon|gun|cookie"]={v=3,d=2,name="Cookie Gun"},
["uncommon|gun|eyes"]={v=3,d=4,name="Eyes"},
["uncommon|gun|fallcamo"]={v=2,d=2,name="Fall Camo"},
["uncommon|gun|floatie"]={v=5,d=0,name="Floatie"},
["uncommon|gun|forrest"]={v=1,d=2,name="Forrest Gun"},
["uncommon|gun|frozen"]={v=5,d=1,name="Frozen Gun"},
["uncommon|gun|gingerbread"]={v=4,d=1,name="Gingerbread Gun"},
["uncommon|gun|gothic"]={v=5,d=2,name="Gothic Gun"},
["uncommon|gun|hazard"]={v=3,d=2,name="Hazard Gun"},
["uncommon|gun|holly"]={v=3,d=1,name="Holly Gun"},
["uncommon|gun|lava"]={v=1,d=2,name="Lava Gun"},
["uncommon|gun|leaves"]={v=5,d=0,name="Leaves"},
["uncommon|gun|lights"]={v=3,d=1,name="Lights Gun"},
["uncommon|gun|love"]={v=5,d=0,name="Love (Gun)"},
["uncommon|gun|marina"]={v=3,d=0.5,name="Marina"},
["uncommon|gun|meadow"]={v=3,d=1,name="Meadow"},
["uncommon|gun|melon"]={v=2,d=2,name="Melon"},
["uncommon|gun|mistletoe"]={v=1,d=2,name="Mistletoe Gun"},
["uncommon|gun|moonlight"]={v=2,d=2,name="Moonlight Gun"},
["uncommon|gun|mummy"]={v=5,d=1,name="Mummy Gun"},
["uncommon|gun|night"]={v=1,d=2,name="Night"},
["uncommon|gun|nutcracker"]={v=1,d=1,name="Nutcracker"},
["uncommon|gun|painted"]={v=3,d=2,name="Painted Gun"},
["uncommon|gun|paws"]={v=1,d=2,name="Paws Gun"},
["uncommon|gun|popsicle"]={v=3,d=0,name="Popsicle Gun"},
["uncommon|gun|portal"]={v=2,d=2,name="Portal gun"},
["uncommon|gun|potion"]={v=2,d=1,name="Potion Gun"},
["uncommon|gun|pumpkinpatch"]={v=1,d=3,name="Pumpkin Patch"},
["uncommon|gun|sketch"]={v=3,d=0,name="Sketch"},
["uncommon|gun|skulls"]={v=17,d=2,name="Skulls"},
["uncommon|gun|snowflake"]={v=3,d=2,name="Snowflake Gun 2022"},
["uncommon|gun|snowman"]={v=4,d=2,name="Snowman Gun"},
["uncommon|gun|soda"]={v=3,d=0,name="Soda"},
["uncommon|gun|stars"]={v=1,d=2,name="Stars Gun"},
["uncommon|gun|stockings"]={v=3,d=2,name="Stockings Gun 2022"},
["uncommon|gun|sweater"]={v=2,d=2,name="Sweater Gun"},
["uncommon|gun|treats"]={v=3,d=3,name="Treats Gun"},
["uncommon|gun|wooden"]={v=3,d=0,name="Wooden"},
["uncommon|gun|wraiths"]={v=2,d=2,name="Wraiths Gun"},
["uncommon|gun|wrap"]={v=20,d=2,name="Wrap Gun"},
["uncommon|gun|wrapped"]={v=1,d=1,name="Wrapped (Gun)"},
["uncommon|gun|zombie"]={v=6,d=1,name="Zombie Gun"},
["uncommon|gun|zombified"]={v=20,d=2,name="ZombifiedGun"},
["uncommon|knife|abduction"]={v=1,d=3,name="Abduction"},
["uncommon|knife|adurite"]={v=3,d=0,name="Adurite (Knife)"},
["uncommon|knife|blossom"]={v=1,d=2,name="Blossom Knife"},
["uncommon|knife|blue"]={v=3,d=0,name="Blue"},
["uncommon|knife|bluesteel"]={v=3,d=0,name="Bluesteel (Knife)"},
["uncommon|knife|bones"]={v=4,d=1,name="Bones"},
["uncommon|knife|brains"]={v=125,d=2.5,name="Brains 2019"},
["uncommon|knife|branches"]={v=55,d=3,name="Branches"},
["uncommon|knife|brush"]={v=3,d=0,name="Brush"},
["uncommon|knife|canes"]={v=3,d=2,name="Canes Knife"},
["uncommon|knife|carrot"]={v=2,d=2,name="Carrot Knife"},
["uncommon|knife|checkers"]={v=1,d=2,name="Checkers"},
["uncommon|knife|cheesy"]={v=3,d=0,name="Cheesy"},
["uncommon|knife|circuit"]={v=3,d=0,name="Circuit"},
["uncommon|knife|cookie"]={v=3,d=2,name="Cookie Knife"},
["uncommon|knife|decorated"]={v=3,d=1,name="Decorated"},
["uncommon|knife|doge"]={v=3,d=0,name="Doge"},
["uncommon|knife|donut"]={v=1,d=2,name="Donut"},
["uncommon|knife|fireplace"]={v=1,d=2,name="Fireplace"},
["uncommon|knife|frosty"]={v=4,d=2,name="Frosty"},
["uncommon|knife|frozen"]={v=2,d=1,name="Frozen Knife"},
["uncommon|knife|future"]={v=1,d=2,name="Future"},
["uncommon|knife|ghostly"]={v=2,d=2,name="Ghostly"},
["uncommon|knife|ghosts"]={v=2,d=2,name="Ghosts knife 2020"},
["uncommon|knife|gifted"]={v=1,d=1,name="Gifted"},
["uncommon|knife|gingerbread"]={v=90,d=2.5,name="Gingerbread Knife"},
["uncommon|knife|gingerheart"]={v=1,d=2,name="Gingerheart"},
["uncommon|knife|gothic"]={v=2,d=2,name="Gothic Knife"},
["uncommon|knife|hazard"]={v=2,d=2,name="Hazard Knife"},
["uncommon|knife|hazmat"]={v=3,d=0,name="Hazmat"},
["uncommon|knife|hive"]={v=3,d=0,name="Hive"},
["uncommon|knife|holly"]={v=2,d=2,name="Holly Knife"},
["uncommon|knife|jellyfish"]={v=3,d=0,name="Jellyfish Knife"},
["uncommon|knife|jigsaw"]={v=3,d=0,name="Jigsaw"},
["uncommon|knife|lantern"]={v=1,d=2,name="Lantern Knife"},
["uncommon|knife|lava"]={v=1,d=2.5,name="Lava Knife"},
["uncommon|knife|lights"]={v=2,d=1,name="Lights Knife"},
["uncommon|knife|lucky"]={v=3,d=0,name="Lucky"},
["uncommon|knife|marble"]={v=3,d=2,name="Marble"},
["uncommon|knife|melon"]={v=3,d=0,name="Melon"},
["uncommon|knife|missing"]={v=3,d=0,name="Missing"},
["uncommon|knife|mistletoe"]={v=4,d=2,name="Mistletoe Knife"},
["uncommon|knife|monster"]={v=3,d=1,name="Monster"},
["uncommon|knife|moons"]={v=3,d=1,name="Moons"},
["uncommon|knife|mummy"]={v=35,d=3,name="Mummy (Knife)"},
["uncommon|knife|paper"]={v=3,d=0,name="Paper"},
["uncommon|knife|pool"]={v=2,d=2,name="Pool Knife"},
["uncommon|knife|poolnoodle"]={v=2,d=2,name="Pool Noodle"},
["uncommon|knife|popsicle"]={v=3,d=2,name="Popsicle"},
["uncommon|knife|potion"]={v=5,d=1,name="Potion Knife"},
["uncommon|knife|pumpkin"]={v=3,d=4,name="Pumpkin"},
["uncommon|knife|pumpkinpie"]={v=1,d=2,name="Pumpkin Pie"},
["uncommon|knife|retro"]={v=1,d=2,name="Retro Knife"},
["uncommon|knife|rose"]={v=2,d=2,name="Rose"},
["uncommon|knife|snowflake"]={v=55,d=3,name="Snowflake Knife"},
["uncommon|knife|snowman"]={v=2,d=2,name="Snowman Knife"},
["uncommon|knife|snowy"]={v=1,d=1,name="Snowy"},
["uncommon|knife|soda"]={v=1,d=2,name="Soda Knife"},
["uncommon|knife|stalker"]={v=3,d=0,name="Stalker"},
["uncommon|knife|starry"]={v=1,d=1,name="Starry Knife"},
["uncommon|knife|stars"]={v=2,d=2,name="Stars Knife"},
["uncommon|knife|stockings"]={v=1,d=2,name="Stockings 2022"},
["uncommon|knife|sweater"]={v=75,d=2.5,name="Sweater Knife"},
["uncommon|knife|treats"]={v=1,d=3,name="Treats knife"},
["uncommon|knife|tree"]={v=3,d=2,name="Tree Knife"},
["uncommon|knife|turtle"]={v=3,d=0,name="Turtle Knife"},
["uncommon|knife|vampire"]={v=2,d=1,name="Vampire"},
["uncommon|knife|void"]={v=15,d=2,name="Void"},
["uncommon|knife|wanwood"]={v=3,d=0,name="Wanwood"},
["uncommon|knife|webs"]={v=3,d=1,name="Webs"},
["uncommon|knife|witchbrew"]={v=2,d=2,name="Witchbrew"},
["uncommon|knife|witchsbrew"]={v=5,d=0,name="Witchs Brew"},
["uncommon|knife|wolf"]={v=4,d=1,name="Wolf"},
["uncommon|knife|wraiths"]={v=3,d=2,name="Wraiths Knife"},
["uncommon|knife|wrap"]={v=18,d=2,name="Wrap Knife"},
["uncommon|knife|wrapped"]={v=3,d=2,name="Wrapped Knife 24"},
["uncommon|knife|wreaths"]={v=3,d=2,name="Wreaths 2024"},
["uncommon|knife|zombie"]={v=13,d=2,name="Zombie"},
["uncommon|knife|zombified"]={v=125,d=3,name="Zombified Knife"},
["unique|gun|blueewrevolver"]={v=50000,d=10,name="Blue EW Revolver"},
["unique|gun|bluegingerscope"]={v=45000,d=10,name="Blue Gingerscope"},
["unique|gun|blueharvester"]={v=45000,d=10,name="Blue Harvester"},
["unique|gun|blueminty"]={v=50000,d=10,name="Blue Minty"},
["unique|gun|bluesugar"]={v=50000,d=10,name="Blue Sugar"},
["unique|gun|blueswirly"]={v=40000,d=10,name="Blue Swirly Gun"},
["unique|gun|bronzeewrevolver"]={v=200000,d=10,name="Bronze EW Revolver"},
["unique|gun|bronzegingerscope"]={v=150000,d=10,name="Bronze Gingerscope"},
["unique|gun|bronzeiceblaster"]={v=200000,d=10,name="Bronze Iceblaster"},
["unique|gun|bronzeicepiercer"]={v=150000,d=10,name="Bronze Icepiercer"},
["unique|gun|bronzeminty"]={v=200000,d=10,name="Bronze Minty"},
["unique|gun|bronzesugar"]={v=200000,d=10,name="Bronze Sugar"},
["unique|gun|bronzeswirly"]={v=100000,d=10,name="Bronze Swirly Gun"},
["unique|gun|corrupt"]={v=325,d=3,name="Corrupt"},
["unique|gun|goldewrevolver"]={v=100000000,d=10,name="Gold EW Revolver"},
["unique|gun|goldgingerscope"]={v=100000000,d=10,name="Gold Gingerscope"},
["unique|gun|goldharvester"]={v=100000000,d=10,name="Gold Harvester"},
["unique|gun|goldiceblaster"]={v=100000000,d=10,name="Gold Iceblaster"},
["unique|gun|goldicepiercer"]={v=100000000,d=10,name="Gold Icepiercer"},
["unique|gun|goldminty"]={v=500000000,d=10,name="Gold Minty"},
["unique|gun|goldsugar"]={v=150000000,d=10,name="Gold Sugar"},
["unique|gun|goldswirly"]={v=100000000,d=10,name="Gold Swirly Gun"},
["unique|gun|rediceblaster"]={v=45000,d=10,name="Red Iceblaster"},
["unique|gun|redicepiercer"]={v=45000,d=10,name="Red Icepiercer"},
["unique|gun|silverewrevolver"]={v=40000000,d=10,name="Silver EW Revolver"},
["unique|gun|silvergingerscope"]={v=2000000,d=10,name="Silver Gingerscope"},
["unique|gun|silverharvester"]={v=2500000,d=10,name="Silver Harvester"},
["unique|gun|silvericeblaster"]={v=35000000,d=10,name="Silver Iceblaster"},
["unique|gun|silvericepiercer"]={v=2000000,d=10,name="Silver Icepiercer"},
["unique|gun|silverminty"]={v=35000000,d=10,name="Silver Minty"},
["unique|gun|silversugar"]={v=45000000,d=10,name="Silver Sugar"},
["unique|gun|silverswirly"]={v=20000000,d=10,name="Silver Swirly Gun"},
["unique|knife|bluecandy"]={v=50000,d=10,name="Blue Candy"},
["unique|knife|blueelderwoodblade"]={v=45000,d=10,name="Blue Elderwood Blade"},
["unique|knife|bluegingerscythe"]={v=40000,d=10,name="Blue Gingerscythe"},
["unique|knife|bluelogchopper"]={v=50000,d=10,name="Blue LogChopper"},
["unique|knife|blueswirlyaxe"]={v=40000,d=10,name="Blue Swirly Axe"},
["unique|knife|bluevampiresedge"]={v=40000,d=10,name="Blue Vampires Edge"},
["unique|knife|bronzecandy"]={v=200000,d=10,name="Bronze Candy"},
["unique|knife|bronzeelderwoodblade"]={v=150000,d=10,name="Bronze Elderwood Blade"},
["unique|knife|bronzegingerscythe"]={v=100000,d=10,name="Bronze Gingerscythe"},
["unique|knife|bronzehallows"]={v=200000,d=10,name="Bronze Hallows"},
["unique|knife|bronzeicebreaker"]={v=200000,d=10,name="Bronze Icebreaker"},
["unique|knife|bronzeicecrusher"]={v=150000,d=10,name="Bronze Icecrusher"},
["unique|knife|bronzelogchopper"]={v=200000,d=10,name="Bronze LogChopper"},
["unique|knife|bronzeswirlyaxe"]={v=100000,d=10,name="Bronze Swirly Axe"},
["unique|knife|bronzetravelersaxe"]={v=100000,d=10,name="Bronze Travelers Axe"},
["unique|knife|bronzevampiresaxe"]={v=100000,d=10,name="Bronze Vampires Axe"},
["unique|knife|bronzevampiresedge"]={v=200000,d=10,name="Bronze Vampires Edge"},
["unique|knife|corrupt"]={v=325,d=3,name="Corrupt"},
["unique|knife|goldcandy"]={v=150000000,d=10,name="Gold Candy"},
["unique|knife|goldedlerwoodblade"]={v=100000000,d=10,name="Gold Edlerwood Blade"},
["unique|knife|goldgingerscythe"]={v=500000000,d=10,name="Gold Gingerscythe"},
["unique|knife|goldhallows"]={v=150000000,d=10,name="Gold Hallows"},
["unique|knife|goldicebreaker"]={v=100000000,d=10,name="Gold Icebreaker"},
["unique|knife|goldicecrusher"]={v=100000000,d=10,name="Gold Icecrusher"},
["unique|knife|goldlogchopper"]={v=500000000,d=10,name="Gold LogChopper"},
["unique|knife|goldswirlyaxe"]={v=100000000,d=10,name="Gold Swirly Axe"},
["unique|knife|goldtravelersaxe"]={v=100000000,d=10,name="Gold Travelers Axe"},
["unique|knife|goldvampiresaxe"]={v=100000000,d=10,name="Gold Vampires Axe"},
["unique|knife|goldvampiresedge"]={v=500000000,d=10,name="Gold Vampires Edge"},
["unique|knife|purplevampiresaxe"]={v=40000,d=10,name="Purple Vampires Axe"},
["unique|knife|redhallows"]={v=50000,d=10,name="Red Hallows"},
["unique|knife|redicebreaker"]={v=45000,d=10,name="Red Icebreaker"},
["unique|knife|redicecrusher"]={v=45000,d=10,name="Red Icecrusher"},
["unique|knife|redtravelersaxe"]={v=40000,d=10,name="Red Travelers Axe"},
["unique|knife|silvercandy"]={v=50000000,d=10,name="Silver Candy"},
["unique|knife|silverelderwoodblade"]={v=2500000,d=10,name="Silver Elderwood Blade"},
["unique|knife|silvergingerscythe"]={v=2000000,d=10,name="Silver Gingerscythe"},
["unique|knife|silverhallows"]={v=50000000,d=10,name="Silver Hallows"},
["unique|knife|silvericebreaker"]={v=35000000,d=10,name="Silver Icebreaker"},
["unique|knife|silvericecrusher"]={v=1000000,d=10,name="Silver Icecrusher"},
["unique|knife|silverlogchopper"]={v=35000000,d=10,name="Silver LogChopper"},
["unique|knife|silverswirlyaxe"]={v=25000000,d=10,name="Silver Swirly Axe"},
["unique|knife|silvertravelersaxe"]={v=1000000,d=10,name="Silver Travelers Axe"},
["unique|knife|silvervampiresaxe"]={v=500000,d=10,name="Silver Vampires Axe"},
["unique|knife|silvervampiresedge"]={v=2000000,d=10,name="Silver Vampires Edge"},
["vintage|knife|blood"]={v=8,d=1,name="Blood"},
},
byTB = {
["gun|ace"]={v=3,d=2,name="Ace"},
["gun|adurite"]={v=3,d=0,name="Adurite (Gun)"},
["gun|amerilaser"]={v=23,d=2,name="Amerilaser"},
["gun|apocalypse"]={v=2,d=2,name="Apocalypse Gun"},
["gun|aquarium"]={v=2,d=1,name="Aquarium Gun"},
["gun|arctic"]={v=12,d=1.5,name="Arctic Gun"},
["gun|aurora"]={v=40,d=2,name="Aurora Gun"},
["gun|bacon"]={v=3,d=2,name="Bacon"},
["gun|balloons"]={v=1,d=0,name="Balloons Gun"},
["gun|bats"]={v=2,d=0,name="Bats"},
["gun|bauble"]={v=675,d=4,name="Bauble"},
["gun|bigkill"]={v=1,d=0,name="Big Kill"},
["gun|bit"]={v=1,d=0,name="Bit"},
["gun|blaster"]={v=17,d=1.5,name="Blaster"},
["gun|blossom"]={v=1380,d=5,name="Blossom"},
["gun|blueewrevolver"]={v=50000,d=10,name="Blue EW Revolver"},
["gun|bluegingerscope"]={v=45000,d=10,name="Blue Gingerscope"},
["gun|blueharvester"]={v=45000,d=10,name="Blue Harvester"},
["gun|blueminty"]={v=50000,d=10,name="Blue Minty"},
["gun|bluesteel"]={v=3,d=0,name="Bluesteel (Gun)"},
["gun|bluesugar"]={v=50000,d=10,name="Blue Sugar"},
["gun|blueswirly"]={v=40000,d=10,name="Blue Swirly Gun"},
["gun|bones"]={v=180,d=2.5,name="Bones Gun"},
["gun|borealis"]={v=140,d=2.5,name="Borealis"},
["gun|brains"]={v=2,d=2,name="Brains Gun"},
["gun|bronzeewrevolver"]={v=200000,d=10,name="Bronze EW Revolver"},
["gun|bronzegingerscope"]={v=150000,d=10,name="Bronze Gingerscope"},
["gun|bronzeiceblaster"]={v=200000,d=10,name="Bronze Iceblaster"},
["gun|bronzeicepiercer"]={v=150000,d=10,name="Bronze Icepiercer"},
["gun|bronzeminty"]={v=200000,d=10,name="Bronze Minty"},
["gun|bronzesugar"]={v=200000,d=10,name="Bronze Sugar"},
["gun|bronzeswirly"]={v=100000,d=10,name="Bronze Swirly Gun"},
["gun|butterflies"]={v=3,d=1,name="Butterflies"},
["gun|camo"]={v=3,d=0,name="Camo"},
["gun|candied"]={v=2,d=0,name="Candied Gun 2022"},
["gun|candleflame"]={v=4,d=2,name="Candleflame"},
["gun|candycorn"]={v=3,d=3,name="Candycorn Gun"},
["gun|candyswirl"]={v=2,d=1,name="Candy Swirl Gun"},
["gun|cane"]={v=2,d=2,name="Cane Gun"},
["gun|canes"]={v=1,d=2,name="Canes Gun"},
["gun|carrot"]={v=2,d=2,name="Carrot Gun"},
["gun|carved"]={v=3,d=0,name="Carved (Gun)"},
["gun|caution"]={v=3,d=0,name="Caution"},
["gun|cavern"]={v=1,d=1,name="Cavern Gun"},
["gun|cheddar"]={v=3,d=0,name="Cheddar"},
["gun|chromabauble"]={v=32000,d=6,name="Chroma Bauble"},
["gun|chromaconstellation"]={v=30000,d=6,name="Chroma Constellation"},
["gun|chromadarkbringer"]={v=60,d=2,name="Chroma Darkbringer"},
["gun|chromaever"]={v=56000,d=6,name="Chroma Evergun"},
["gun|chromalaser"]={v=40,d=2,name="Chroma Laser"},
["gun|chromalightbringer"]={v=55,d=2,name="Chroma Lightbringer"},
["gun|chromaluger"]={v=48,d=2,name="Chroma Luger"},
["gun|chromaray"]={v=14000,d=5,name="Chroma Raygun"},
["gun|chromashark"]={v=33,d=1.5,name="Chroma Shark"},
["gun|chromasunrise"]={v=10500,d=5,name="Chroma Sunrise"},
["gun|chromaswirly"]={v=35,d=1,name="Chroma Swirlygun"},
["gun|chromatic"]={v=3,d=2,name="Chromatic Gun"},
["gun|chromatravelers"]={v=145000,d=7,name="Chroma Travelers Gun"},
["gun|chromatreat"]={v=1800,d=4.5,name="Chroma Treat"},
["gun|chromawater"]={v=2550,d=4,name="Chroma WaterGun"},
["gun|clown"]={v=3,d=1,name="Clown"},
["gun|clownfish"]={v=1,d=0,name="Clownfish Gun"},
["gun|coal"]={v=1,d=2,name="Coal Gun 2022"},
["gun|cold"]={v=1,d=0,name="Cold"},
["gun|constellation"]={v=2725,d=5,name="Constellation"},
["gun|cookie"]={v=3,d=2,name="Cookie Gun"},
["gun|corrupt"]={v=325,d=3,name="Corrupt"},
["gun|cursed"]={v=1,d=1,name="Cursed"},
["gun|darkbringer"]={v=35,d=2,name="Darkbringer"},
["gun|darkness"]={v=3,d=0,name="Darkness Gun"},
["gun|elderwoodrevolver"]={v=35,d=2,name="Elderwood Revolver"},
["gun|elf"]={v=3,d=1,name="Elf (Gun)"},
["gun|energized"]={v=2,d=2,name="Energized Gun"},
["gun|engraved"]={v=1,d=0,name="Engraved"},
["gun|ever"]={v=3425,d=5,name="Evergun"},
["gun|eyes"]={v=3,d=4,name="Eyes"},
["gun|fall"]={v=1,d=3,name="Fall"},
["gun|fallcamo"]={v=2,d=2,name="Fall Camo"},
["gun|fallout"]={v=1,d=0,name="Fallout"},
["gun|floatie"]={v=5,d=0,name="Floatie"},
["gun|flora"]={v=410,d=4.5,name="Flora"},
["gun|floral"]={v=2,d=1,name="Floral Gun"},
["gun|flowerwood"]={v=260,d=4,name="Flowerwood Gun"},
["gun|forrest"]={v=1,d=2,name="Forrest Gun"},
["gun|fragile"]={v=2,d=0,name="Fragile Gun"},
["gun|frostfade"]={v=3,d=2,name="Frostfade Gun"},
["gun|frostflame"]={v=1,d=2,name="Frostflame Gun"},
["gun|frozen"]={v=5,d=1,name="Frozen Gun"},
["gun|galactic"]={v=3,d=2,name="Galactic"},
["gun|ghastly"]={v=12,d=2,name="Ghastly Gun"},
["gun|ghost"]={v=1,d=1,name="Ghost Gun"},
["gun|ghostfire"]={v=15,d=2,name="Ghostfire"},
["gun|ghosts"]={v=2,d=2,name="Ghosts"},
["gun|ginger"]={v=5,d=1,name="Ginger Gun"},
["gun|gingerbread"]={v=4,d=1,name="Gingerbread Gun"},
["gun|gingermint"]={v=14,d=1,name="Gingermint"},
["gun|gingerscope"]={v=16000,d=5,name="Gingerscope"},
["gun|goldewrevolver"]={v=100000000,d=10,name="Gold EW Revolver"},
["gun|goldgingerscope"]={v=100000000,d=10,name="Gold Gingerscope"},
["gun|goldharvester"]={v=100000000,d=10,name="Gold Harvester"},
["gun|goldiceblaster"]={v=100000000,d=10,name="Gold Iceblaster"},
["gun|goldicepiercer"]={v=100000000,d=10,name="Gold Icepiercer"},
["gun|goldminty"]={v=500000000,d=10,name="Gold Minty"},
["gun|goldsugar"]={v=150000000,d=10,name="Gold Sugar"},
["gun|goldswirly"]={v=100000000,d=10,name="Gold Swirly Gun"},
["gun|gothic"]={v=5,d=2,name="Gothic Gun"},
["gun|greenluger"]={v=25,d=2,name="Green Luger"},
["gun|hacker"]={v=3,d=2,name="Hacker"},
["gun|hallow"]={v=22,d=2,name="Hallowgun"},
["gun|harvester"]={v=250,d=3,name="Harvester"},
["gun|hazard"]={v=3,d=2,name="Hazard Gun"},
["gun|heartbreak"]={v=3,d=2,name="Heartbreak"},
["gun|hl2"]={v=1,d=0,name="HL2"},
["gun|holly"]={v=3,d=1,name="Holly Gun"},
["gun|hologram"]={v=3,d=2,name="Hologram Gun"},
["gun|icebeam"]={v=20,d=1.5,name="Icebeam"},
["gun|iceblaster"]={v=35,d=2,name="Iceblaster"},
["gun|icepiercer"]={v=165,d=2.5,name="Icepiercer"},
["gun|icicles"]={v=3,d=1,name="Icicles Gun"},
["gun|igloo"]={v=3,d=0,name="Igloo Gun"},
["gun|imbued"]={v=3,d=2,name="Imbued"},
["gun|infected"]={v=3,d=2,name="Infected Gun"},
["gun|infiltrator"]={v=1,d=0,name="Infiltrator"},
["gun|irevolver"]={v=3,d=2,name="iRevolver"},
["gun|iron"]={v=1,d=0,name="Iron"},
["gun|jingle"]={v=15,d=2,name="Jinglegun"},
["gun|juice"]={v=1,d=0,name="Juice"},
["gun|laser"]={v=23,d=2,name="Laser"},
["gun|latte"]={v=145,d=2,name="Latte Gun"},
["gun|lava"]={v=1,d=2,name="Lava Gun"},
["gun|leaves"]={v=5,d=0,name="Leaves"},
["gun|lightbringer"]={v=33,d=2,name="Lightbringer"},
["gun|lights"]={v=3,d=1,name="Lights Gun"},
["gun|love"]={v=5,d=0,name="Love (Gun)"},
["gun|luger"]={v=17,d=1,name="Luger"},
["gun|lugercane"]={v=15,d=2,name="Luger Cane"},
["gun|magma"]={v=10,d=2,name="Magma Gun"},
["gun|makeshift"]={v=33,d=1,name="Makeshift"},
["gun|marina"]={v=3,d=0.5,name="Marina"},
["gun|meadow"]={v=3,d=1,name="Meadow"},
["gun|melon"]={v=2,d=2,name="Melon"},
["gun|minty"]={v=15,d=1,name="Minty"},
["gun|mistletoe"]={v=1,d=2,name="Mistletoe Gun"},
["gun|molten"]={v=2,d=2,name="Molten (Gun)"},
["gun|monster"]={v=4,d=1,name="Monster"},
["gun|moonlight"]={v=2,d=2,name="Moonlight Gun"},
["gun|mummy"]={v=5,d=1,name="Mummy Gun"},
["gun|neon"]={v=3,d=2,name="Neon Gun"},
["gun|news"]={v=1,d=0,name="News"},
["gun|night"]={v=1,d=2,name="Night"},
["gun|nightfire"]={v=3,d=2,name="Nightfire"},
["gun|nightsky"]={v=1,d=1.5,name="Nightsky"},
["gun|nuclear"]={v=2,d=2.5,name="Nuclear"},
["gun|nutcracker"]={v=1,d=1,name="Nutcracker"},
["gun|ocean"]={v=280,d=4,name="Ocean"},
["gun|overseer"]={v=4,d=2.5,name="Overseer (gun)"},
["gun|painted"]={v=3,d=2,name="Painted Gun"},
["gun|palms"]={v=2,d=2,name="Palms Gun"},
["gun|paws"]={v=1,d=2,name="Paws Gun"},
["gun|pea"]={v=1,d=0,name="Pea"},
["gun|pearlshine"]={v=80,d=2,name="Pearlshine"},
["gun|plaid"]={v=0,d=0,name="Plaid Gun"},
["gun|plasmabeam"]={v=20,d=1.5,name="Plasmabeam"},
["gun|popart"]={v=2,d=2,name="Pop Art Gun"},
["gun|popsicle"]={v=3,d=0,name="Popsicle Gun"},
["gun|portal"]={v=2,d=2,name="Portal gun"},
["gun|potion"]={v=2,d=1,name="Potion Gun"},
["gun|predator"]={v=4,d=3,name="Predator (gun)"},
["gun|pumpkinpatch"]={v=1,d=3,name="Pumpkin Patch"},
["gun|rainbow"]={v=430,d=5,name="Rainbow Gun"},
["gun|ray"]={v=1875,d=5,name="Raygun"},
["gun|rediceblaster"]={v=45000,d=10,name="Red Iceblaster"},
["gun|redicepiercer"]={v=45000,d=10,name="Red Icepiercer"},
["gun|redluger"]={v=38,d=2,name="Red Luger"},
["gun|ripper"]={v=3,d=2,name="Ripper Gun"},
["gun|ritual"]={v=1,d=1,name="Ritual"},
["gun|rupture"]={v=1,d=1,name="Rupture"},
["gun|sandy"]={v=1,d=0,name="Sandy Gun"},
["gun|santa"]={v=2,d=0,name="Santa Gun 23"},
["gun|shark"]={v=20,d=2,name="Shark"},
["gun|silentnight"]={v=15,d=1.5,name="Silent Night Gun"},
["gun|silverewrevolver"]={v=40000000,d=10,name="Silver EW Revolver"},
["gun|silvergingerscope"]={v=2000000,d=10,name="Silver Gingerscope"},
["gun|silverharvester"]={v=2500000,d=10,name="Silver Harvester"},
["gun|silvericeblaster"]={v=35000000,d=10,name="Silver Iceblaster"},
["gun|silvericepiercer"]={v=2000000,d=10,name="Silver Icepiercer"},
["gun|silverminty"]={v=35000000,d=10,name="Silver Minty"},
["gun|silversugar"]={v=45000000,d=10,name="Silver Sugar"},
["gun|silverswirly"]={v=20000000,d=10,name="Silver Swirly Gun"},
["gun|sketch"]={v=3,d=0,name="Sketch"},
["gun|skulls"]={v=17,d=2,name="Skulls"},
["gun|snakebite"]={v=1,d=1,name="Snakebite Gun"},
["gun|snowflake"]={v=3,d=2,name="Snowflake Gun 2022"},
["gun|snowman"]={v=4,d=2,name="Snowman Gun"},
["gun|soda"]={v=3,d=0,name="Soda"},
["gun|soul"]={v=650,d=5,name="Soul"},
["gun|sparkle"]={v=3,d=2,name="Sparkle"},
["gun|spectral"]={v=4,d=2.5,name="Spectral Gun"},
["gun|spectre"]={v=37,d=1,name="Spectre"},
["gun|splash"]={v=3,d=1,name="Splash Gun"},
["gun|star"]={v=1,d=0,name="Star"},
["gun|starfish"]={v=1,d=0,name="Starfish Gun"},
["gun|starry"]={v=20,d=2,name="Starry Gun"},
["gun|stars"]={v=1,d=2,name="Stars Gun"},
["gun|sticker"]={v=2,d=0,name="Sticker Gun"},
["gun|stickers"]={v=3,d=0,name="Stickers Knife"},
["gun|stickersxmas"]={v=2,d=1,name="Stickers Xmas 24"},
["gun|stockings"]={v=3,d=2,name="Stockings Gun 2022"},
["gun|strawberries"]={v=4,d=2,name="Strawberries Gun"},
["gun|striped"]={v=2,d=1.5,name="Striped Gun"},
["gun|sugar"]={v=33,d=1.5,name="Sugar"},
["gun|sunny"]={v=1,d=1,name="Sunny"},
["gun|sunset"]={v=675,d=4,name="Sunset"},
["gun|sweater"]={v=2,d=2,name="Sweater Gun"},
["gun|swirly"]={v=18,d=1,name="Swirlygun"},
["gun|toxic"]={v=2,d=1,name="Toxic Gun"},
["gun|toy"]={v=3,d=0,name="Toy Gun"},
["gun|traveler"]={v=45,d=2,name="Traveler Gun"},
["gun|travelers"]={v=5150,d=5,name="Travelers Gun"},
["gun|treat"]={v=155,d=2.5,name="Treat"},
["gun|treats"]={v=3,d=3,name="Treats Gun"},
["gun|tree"]={v=3,d=2,name="Tree Gun 2022"},
["gun|ufos"]={v=1,d=3,name="UFOs Gun"},
["gun|universe"]={v=3,d=2,name="Universe"},
["gun|vampire"]={v=40,d=2,name="Vampire Gun"},
["gun|vampires"]={v=1875,d=5,name="Vampires Gun"},
["gun|viper"]={v=3,d=2,name="Viper"},
["gun|watcher"]={v=20,d=3,name="Watcher Gun"},
["gun|water"]={v=160,d=2,name="WaterGun"},
["gun|wavy"]={v=3,d=0,name="Wavy Gun"},
["gun|webs"]={v=1,d=2,name="Webs Gun"},
["gun|wooden"]={v=3,d=0,name="Wooden"},
["gun|wraith"]={v=2,d=2,name="Wraith Gun"},
["gun|wraiths"]={v=2,d=2,name="Wraiths Gun"},
["gun|wrap"]={v=20,d=2,name="Wrap Gun"},
["gun|wrapped"]={v=1,d=1,name="Wrapped (Gun)"},
["gun|xeno"]={v=3,d=3,name="Xeno Gun"},
["gun|xenoshot"]={v=420,d=4.5,name="Xenoshot"},
["gun|zombie"]={v=6,d=1,name="Zombie Gun"},
["gun|zombified"]={v=20,d=2,name="ZombifiedGun"},
["knife|8bit"]={v=1,d=0,name="8Bit"},
["knife|abduction"]={v=1,d=3,name="Abduction"},
["knife|abstract"]={v=3,d=2,name="Abstract"},
["knife|adurite"]={v=3,d=0,name="Adurite (Knife)"},
["knife|alienbeam"]={v=2000,d=5,name="Alienbeam"},
["knife|apocalypse"]={v=1,d=2,name="Apocalypse Knife"},
["knife|aqua"]={v=1,d=0,name="Aqua"},
["knife|aquarium"]={v=2,d=1,name="Aquarium Knife"},
["knife|arctic"]={v=3,d=3,name="Arctic Knife"},
["knife|aurora"]={v=7,d=1.5,name="Aurora Knife"},
["knife|australis"]={v=135,d=2.5,name="Australis"},
["knife|bat"]={v=120,d=2,name="Bat"},
["knife|bats"]={v=3,d=2,name="Bats"},
["knife|battleaxe"]={v=13,d=1,name="BattleAxe"},
["knife|batwing"]={v=45,d=2,name="Batwing"},
["knife|beach"]={v=35,d=2,name="Beach"},
["knife|bells"]={v=2,d=0,name="Bells"},
["knife|bioblade"]={v=10,d=1,name="Bioblade"},
["knife|biogel"]={v=3,d=2,name="Biogel"},
["knife|bleached"]={v=1,d=0,name="Bleached"},
["knife|blood"]={v=8,d=1,name="Blood"},
["knife|bloom"]={v=400,d=4.5,name="Bloom"},
["knife|blossom"]={v=1,d=2,name="Blossom Knife"},
["knife|blue"]={v=3,d=0,name="Blue"},
["knife|bluecandy"]={v=50000,d=10,name="Blue Candy"},
["knife|blueelderwoodblade"]={v=45000,d=10,name="Blue Elderwood Blade"},
["knife|blueelite"]={v=4,d=1,name="Blue Elite"},
["knife|bluegingerscythe"]={v=40000,d=10,name="Blue Gingerscythe"},
["knife|bluelogchopper"]={v=50000,d=10,name="Blue LogChopper"},
["knife|bluescratch"]={v=3,d=1,name="Blue Scratch"},
["knife|blueseer"]={v=3,d=1,name="Blue Seer"},
["knife|bluesteel"]={v=3,d=0,name="Bluesteel (Knife)"},
["knife|blueswirlyaxe"]={v=40000,d=10,name="Blue Swirly Axe"},
["knife|bluevampiresedge"]={v=40000,d=10,name="Blue Vampires Edge"},
["knife|boneblade"]={v=8,d=1,name="Boneblade"},
["knife|bones"]={v=4,d=1,name="Bones"},
["knife|borders"]={v=1,d=0,name="Borders"},
["knife|brains"]={v=125,d=2.5,name="Brains 2019"},
["knife|branches"]={v=55,d=3,name="Branches"},
["knife|broken"]={v=7,d=2,name="Broken"},
["knife|bronzecandy"]={v=200000,d=10,name="Bronze Candy"},
["knife|bronzeelderwoodblade"]={v=150000,d=10,name="Bronze Elderwood Blade"},
["knife|bronzegingerscythe"]={v=100000,d=10,name="Bronze Gingerscythe"},
["knife|bronzehallows"]={v=200000,d=10,name="Bronze Hallows"},
["knife|bronzeicebreaker"]={v=200000,d=10,name="Bronze Icebreaker"},
["knife|bronzeicecrusher"]={v=150000,d=10,name="Bronze Icecrusher"},
["knife|bronzelogchopper"]={v=200000,d=10,name="Bronze LogChopper"},
["knife|bronzeswirlyaxe"]={v=100000,d=10,name="Bronze Swirly Axe"},
["knife|bronzetravelersaxe"]={v=100000,d=10,name="Bronze Travelers Axe"},
["knife|bronzevampiresaxe"]={v=100000,d=10,name="Bronze Vampires Axe"},
["knife|bronzevampiresedge"]={v=200000,d=10,name="Bronze Vampires Edge"},
["knife|brush"]={v=3,d=0,name="Brush"},
["knife|bunnies"]={v=4,d=2,name="Bunnies"},
["knife|candied"]={v=1,d=2,name="Candied Knife"},
["knife|candle"]={v=2,d=0,name="Candle"},
["knife|candleflame"]={v=35,d=2,name="Candleflame"},
["knife|candles"]={v=2,d=0,name="Candles"},
["knife|candy"]={v=90,d=2,name="Candy"},
["knife|candycorn"]={v=12,d=2,name="Candycorn 2019"},
["knife|candyswirl"]={v=1,d=2,name="Candy Swirl Knife"},
["knife|cane"]={v=525,d=4,name="Cane Knife"},
["knife|canes"]={v=3,d=2,name="Canes Knife"},
["knife|cardboard"]={v=1,d=0,name="Cardboard"},
["knife|carrot"]={v=2,d=2,name="Carrot Knife"},
["knife|carrots"]={v=1,d=0,name="Carrots"},
["knife|carved"]={v=3,d=0,name="Carved (Knife)"},
["knife|cats"]={v=3,d=3,name="Cats"},
["knife|cavern"]={v=8,d=1.5,name="Cavern Knife"},
["knife|celestial"]={v=2250,d=5,name="Celestial"},
["knife|checkers"]={v=1,d=2,name="Checkers"},
["knife|cheesy"]={v=3,d=0,name="Cheesy"},
["knife|cherry"]={v=1,d=0,name="Cherry"},
["knife|chick"]={v=1,d=0,name="Chick"},
["knife|chill"]={v=12,d=1,name="Chill"},
["knife|chromaalienbeam"]={v=23000,d=6,name="Chroma Alienbeam"},
["knife|chromaboneblade"]={v=20,d=1,name="Chroma Boneblade"},
["knife|chromacandleflame"]={v=40,d=1,name="Chroma Candleflame"},
["knife|chromacookiecane"]={v=30,d=1,name="Chroma Cookiecane"},
["knife|chromadeathshard"]={v=35,d=1,name="Chroma DeathShard"},
["knife|chromaelderwoodblade"]={v=35,d=1,name="Chroma Elderwood Blade"},
["knife|chromaevergreen"]={v=41000,d=6,name="Chroma Evergreen"},
["knife|chromafang"]={v=33,d=1,name="Chroma Fang"},
["knife|chromagemstone"]={v=33,d=1,name="Chroma Gemstone"},
["knife|chromagingerblade"]={v=25,d=1,name="Chroma Gingerblade"},
["knife|chromaheartwand"]={v=4000,d=4.5,name="Chroma Heart Wand"},
["knife|chromaheat"]={v=30,d=1,name="Chroma Heat"},
["knife|chromasaw"]={v=22,d=1,name="Chroma Saw"},
["knife|chromaseer"]={v=25,d=1,name="Chroma Seer"},
["knife|chromaslasher"]={v=33,d=2,name="Chroma Slasher"},
["knife|chromasunset"]={v=7750,d=6,name="Chroma Sunset"},
["knife|chromasweet"]={v=1750,d=4.5,name="Chroma Sweet"},
["knife|chromatic"]={v=4,d=2,name="Chromatic Knife"},
["knife|chromatides"]={v=25,d=1,name="Chroma Tides"},
["knife|circuit"]={v=3,d=0,name="Circuit"},
["knife|clan"]={v=1,d=0,name="Clan"},
["knife|clockwork"]={v=12,d=1,name="Clockwork"},
["knife|clown"]={v=1,d=0,name="Clown"},
["knife|clownfish"]={v=1,d=0,name="Clownfish Knife"},
["knife|coal"]={v=2,d=0,name="Coal Knife 2022"},
["knife|coconut"]={v=1,d=1.5,name="Coconut Knife"},
["knife|combatii"]={v=11,d=2,name="Combat II"},
["knife|cookie"]={v=3,d=2,name="Cookie Knife"},
["knife|cookieblade"]={v=4,d=1,name="Cookieblade"},
["knife|cookiecane"]={v=14,d=1,name="Cookiecane"},
["knife|corrupt"]={v=325,d=3,name="Corrupt"},
["knife|cottoncandy"]={v=40,d=2,name="Cotton Candy"},
["knife|cupid"]={v=1,d=3,name="Cupid"},
["knife|curse"]={v=2,d=2,name="Curse Knife"},
["knife|cursed"]={v=1,d=1,name="Cursed"},
["knife|damp"]={v=3,d=2,name="Damp"},
["knife|dark"]={v=65,d=3,name="DarkKnife"},
["knife|darkness"]={v=1,d=2,name="Darkness Knife"},
["knife|deathshard"]={v=13,d=1,name="Death Shard"},
["knife|decorated"]={v=3,d=1,name="Decorated"},
["knife|deepsea"]={v=3,d=2,name="Deep Sea"},
["knife|doge"]={v=3,d=0,name="Doge"},
["knife|dolphins"]={v=1,d=1.5,name="Dolphins Knife"},
["knife|donut"]={v=1,d=2,name="Donut"},
["knife|dungeon"]={v=135,d=2.5,name="Dungeon"},
["knife|eco"]={v=1,d=0,name="Eco"},
["knife|eggblade"]={v=5,d=1,name="Eggblade"},
["knife|elderwoodblade"]={v=32,d=1,name="Elderwood Blade"},
["knife|elderwoodscythe"]={v=40,d=2,name="Elderwood Scythe"},
["knife|elf"]={v=1,d=2,name="Elf (2017)"},
["knife|elite"]={v=3,d=1,name="Elite"},
["knife|emerald"]={v=4,d=2,name="Emerald"},
["knife|energized"]={v=1,d=2,name="Energized Knife"},
["knife|eternal"]={v=10,d=1,name="Eternal"},
["knife|eternalcane"]={v=13,d=1.5,name="Eternal Cane"},
["knife|eternalii"]={v=8,d=1,name="Eternal II"},
["knife|eternaliii"]={v=10,d=1,name="Eternal III"},
["knife|eternaliv"]={v=10,d=1,name="Eternal IV"},
["knife|evergreen"]={v=2550,d=5,name="Evergreen"},
["knife|eyeball"]={v=3,d=0,name="Eyeball Knife"},
["knife|fade"]={v=3,d=2,name="Fade"},
["knife|fang"]={v=12,d=1,name="Fang"},
["knife|fireplace"]={v=1,d=2,name="Fireplace"},
["knife|flames"]={v=7,d=1,name="Flames"},
["knife|floral"]={v=12,d=2,name="Floral"},
["knife|flowerwood"]={v=255,d=4,name="Flowerwood Knife"},
["knife|fragile"]={v=2,d=0,name="Fragile Knife"},
["knife|frostbite"]={v=7,d=1,name="Frostbite"},
["knife|frostfade"]={v=2,d=1.5,name="Frostfade Knife"},
["knife|frostflame"]={v=3,d=2,name="Frostflame Knife"},
["knife|frostsaber"]={v=10,d=1,name="Frostsaber"},
["knife|frosty"]={v=4,d=2,name="Frosty"},
["knife|frozen"]={v=2,d=1,name="Frozen Knife"},
["knife|fusion"]={v=3,d=2,name="Fusion"},
["knife|future"]={v=1,d=2,name="Future"},
["knife|galaxy"]={v=3,d=2,name="Galaxy"},
["knife|gemstone"]={v=13,d=1,name="Gemstone"},
["knife|ghost"]={v=5,d=1,name="Ghost Knife"},
["knife|ghostblade"]={v=8,d=1,name="Ghost Blade"},
["knife|ghostly"]={v=2,d=2,name="Ghostly"},
["knife|ghosts"]={v=2,d=2,name="Ghosts knife 2020"},
["knife|giftbag"]={v=3,d=2,name="Gift Bag Knife"},
["knife|gifted"]={v=1,d=1,name="Gifted"},
["knife|gifts"]={v=3,d=0,name="Gifts 2024"},
["knife|ginger"]={v=3,d=1,name="Ginger (Knife)"},
["knife|gingerblade"]={v=13,d=1,name="Gingerblade"},
["knife|gingerbread"]={v=90,d=2.5,name="Gingerbread Knife"},
["knife|gingerheart"]={v=1,d=2,name="Gingerheart"},
["knife|glitch1"]={v=60,d=2.5,name="Glitch 1"},
["knife|glitch2"]={v=30,d=1,name="Glitch 2"},
["knife|goldcandy"]={v=150000000,d=10,name="Gold Candy"},
["knife|goldedlerwoodblade"]={v=100000000,d=10,name="Gold Edlerwood Blade"},
["knife|goldgingerscythe"]={v=500000000,d=10,name="Gold Gingerscythe"},
["knife|goldhallows"]={v=150000000,d=10,name="Gold Hallows"},
["knife|goldicebreaker"]={v=100000000,d=10,name="Gold Icebreaker"},
["knife|goldicecrusher"]={v=100000000,d=10,name="Gold Icecrusher"},
["knife|goldlogchopper"]={v=500000000,d=10,name="Gold LogChopper"},
["knife|goldswirlyaxe"]={v=100000000,d=10,name="Gold Swirly Axe"},
["knife|goldtravelersaxe"]={v=100000000,d=10,name="Gold Travelers Axe"},
["knife|goldvampiresaxe"]={v=100000000,d=10,name="Gold Vampires Axe"},
["knife|goldvampiresedge"]={v=500000000,d=10,name="Gold Vampires Edge"},
["knife|gothic"]={v=2,d=2,name="Gothic Knife"},
["knife|greenelite"]={v=4,d=1,name="Green Elite"},
["knife|greenfire"]={v=3,d=1,name="Green Fire"},
["knife|greenmarble"]={v=3,d=1,name="Green Marble"},
["knife|hallowsblade"]={v=7,d=1,name="Hallows Blade"},
["knife|hallowscythe"]={v=32,d=2,name="Hallowscythe"},
["knife|hallowsedge"]={v=9,d=1,name="Hallows Edge"},
["knife|handsaw"]={v=9,d=1,name="Handsaw"},
["knife|haunted"]={v=3,d=3,name="Haunted"},
["knife|hazard"]={v=2,d=2,name="Hazard Knife"},
["knife|hazmat"]={v=3,d=0,name="Hazmat"},
["knife|heart"]={v=1,d=2,name="Heart"},
["knife|heartblade"]={v=65,d=2,name="Heartblade"},
["knife|hearts"]={v=4,d=2,name="Hearts Knife"},
["knife|heartwand"]={v=350,d=4.5,name="Heart Wand"},
["knife|heat"]={v=12,d=1,name="Heat"},
["knife|hive"]={v=3,d=0,name="Hive"},
["knife|holly"]={v=2,d=2,name="Holly Knife"},
["knife|hologram"]={v=3,d=3,name="Hologram Knife"},
["knife|hotchocolate"]={v=3,d=0,name="Hot Chocolate"},
["knife|hunter"]={v=1,d=2,name="Hunter Knife"},
["knife|ice"]={v=1,d=0,name="Ice"},
["knife|icebreaker"]={v=70,d=2,name="Icebreaker"},
["knife|icecracker"]={v=2,d=1,name="Icecracker"},
["knife|icedragon"]={v=7,d=1,name="Ice Dragon"},
["knife|icedriller"]={v=6,d=1,name="Icedriller"},
["knife|iceflake"]={v=18,d=1.5,name="Iceflake"},
["knife|iceshard"]={v=9,d=1,name="Ice Shard"},
["knife|icewing"]={v=15,d=2,name="Ice Wing"},
["knife|icicles"]={v=1,d=2,name="Icicles Knife"},
["knife|igloo"]={v=2,d=0,name="Igloo Knife"},
["knife|infected"]={v=1,d=2,name="Infected Knife"},
["knife|jack"]={v=3,d=1.5,name="Jack"},
["knife|jd"]={v=30,d=2,name="JD"},
["knife|jellyfish"]={v=3,d=0,name="Jellyfish Knife"},
["knife|jigsaw"]={v=3,d=0,name="Jigsaw"},
["knife|korblox"]={v=3,d=2,name="Korblox"},
["knife|kraken"]={v=1,d=1,name="Kraken"},
["knife|krypto"]={v=3,d=2,name="Krypto"},
["knife|lantern"]={v=1,d=2,name="Lantern Knife"},
["knife|latte"]={v=145,d=2,name="Latte Knife"},
["knife|lava"]={v=1,d=2.5,name="Lava Knife"},
["knife|leaves"]={v=1,d=1.5,name="Leaves Knife"},
["knife|lights"]={v=2,d=1,name="Lights Knife"},
["knife|linked"]={v=1,d=0,name="Linked"},
["knife|log"]={v=1,d=0,name="Log"},
["knife|logchopper"]={v=20,d=1.5,name="Log Chopper"},
["knife|logcutter"]={v=3,d=2,name="Logcutter"},
["knife|love"]={v=1,d=2,name="Love"},
["knife|lucky"]={v=3,d=0,name="Lucky"},
["knife|magma"]={v=7,d=1.5,name="Magma"},
["knife|makeshift"]={v=40,d=3,name="Makeshift Knife"},
["knife|marble"]={v=3,d=2,name="Marble"},
["knife|melon"]={v=3,d=0,name="Melon"},
["knife|midnight"]={v=3,d=2,name="Midnight"},
["knife|missing"]={v=3,d=0,name="Missing"},
["knife|mistletoe"]={v=4,d=2,name="Mistletoe Knife"},
["knife|molten"]={v=2,d=2,name="Molten (Knife)"},
["knife|monster"]={v=3,d=1,name="Monster"},
["knife|moons"]={v=3,d=1,name="Moons"},
["knife|mummy"]={v=35,d=3,name="Mummy (Knife)"},
["knife|musical"]={v=3,d=2,name="Musical"},
["knife|nebula"]={v=13,d=1,name="Nebula"},
["knife|nether"]={v=3,d=2,name="Nether"},
["knife|nightblade"]={v=20,d=1.5,name="Night Blade"},
["knife|nightstar"]={v=2,d=2,name="Nightstar"},
["knife|niksscythe"]={v=250000000,d=11,name="Niks Scythe"},
["knife|nova"]={v=3,d=2,name="Nova"},
["knife|oily"]={v=1,d=0,name="Oily"},
["knife|oldglory"]={v=17,d=1.5,name="Old Glory"},
["knife|ollie"]={v=8,d=2,name="Ollie"},
["knife|orangemarble"]={v=2,d=1,name="Orange Marble"},
["knife|orangeseer"]={v=2,d=1,name="Orange Seer"},
["knife|ornament1"]={v=1,d=1,name="Ornament 1"},
["knife|overseer"]={v=4,d=3,name="Overseer (knife)"},
["knife|painted"]={v=1,d=2,name="Painted Knife"},
["knife|palms"]={v=2,d=1,name="Palms Knife"},
["knife|paper"]={v=3,d=0,name="Paper"},
["knife|passion"]={v=1,d=2,name="Passion"},
["knife|pearl"]={v=75,d=2,name="Pearl"},
["knife|phantom"]={v=37,d=1,name="Phantom"},
["knife|pixel"]={v=18,d=1.5,name="Pixel"},
["knife|plasmablade"]={v=17,d=1,name="Plasmablade"},
["knife|plasmite"]={v=3,d=2,name="Plasmite"},
["knife|pool"]={v=2,d=2,name="Pool Knife"},
["knife|poolnoodle"]={v=2,d=2,name="Pool Noodle"},
["knife|popart"]={v=2,d=2,name="Pop Art Knife"},
["knife|popsicle"]={v=3,d=2,name="Popsicle"},
["knife|portal"]={v=3,d=2,name="Portal Knife"},
["knife|potion"]={v=5,d=1,name="Potion Knife"},
["knife|predator"]={v=4,d=2.5,name="Predator (knife)"},
["knife|present"]={v=2,d=0,name="Present Knife"},
["knife|prismatic"]={v=5,d=1,name="Prismatic"},
["knife|pumpkin"]={v=3,d=4,name="Pumpkin"},
["knife|pumpking"]={v=8,d=1,name="Pumpking"},
["knife|pumpkinpie"]={v=1,d=2,name="Pumpkin Pie"},
["knife|purpleseer"]={v=3,d=1,name="Purple Seer"},
["knife|purplevampiresaxe"]={v=40000,d=10,name="Purple Vampires Axe"},
["knife|rainbow"]={v=430,d=5,name="Rainbow Gun"},
["knife|rb"]={v=1,d=2,name="RB Knife"},
["knife|redfire"]={v=2,d=1,name="Red Fire"},
["knife|redhallows"]={v=50000,d=10,name="Red Hallows"},
["knife|redicebreaker"]={v=45000,d=10,name="Red Icebreaker"},
["knife|redicecrusher"]={v=45000,d=10,name="Red Icecrusher"},
["knife|redseer"]={v=3,d=1,name="Red Seer"},
["knife|redtravelersaxe"]={v=40000,d=10,name="Red Travelers Axe"},
["knife|reindeer"]={v=2,d=0,name="Reindeer 2024"},
["knife|retro"]={v=1,d=2,name="Retro Knife"},
["knife|ribbon"]={v=2,d=0,name="Ribbon Knife"},
["knife|ripper"]={v=4,d=2,name="Ripper Knife"},
["knife|robot"]={v=2,d=2,name="Robot Knife"},
["knife|rose"]={v=2,d=2,name="Rose"},
["knife|roses"]={v=1,d=2,name="Roses"},
["knife|rune"]={v=3,d=2,name="Rune"},
["knife|sakura"]={v=1360,d=5,name="Sakura"},
["knife|sandy"]={v=1,d=0,name="Sandy"},
["knife|santasmagic"]={v=5,d=1,name="Santas Magic"},
["knife|santasspirit"]={v=5,d=1,name="Santas Spirit"},
["knife|saw"]={v=8,d=1,name="Saw"},
["knife|scarf"]={v=1,d=2,name="Scarf"},
["knife|scratch"]={v=4,d=1,name="Scratch"},
["knife|seer"]={v=3,d=1,name="Seer"},
["knife|sharkie"]={v=1,d=2,name="Sharkie Knife"},
["knife|shiny"]={v=3,d=2,name="Shiny"},
["knife|silentnight"]={v=50,d=1.5,name="Silent Night Knife"},
["knife|silvercandy"]={v=50000000,d=10,name="Silver Candy"},
["knife|silverelderwoodblade"]={v=2500000,d=10,name="Silver Elderwood Blade"},
["knife|silvergingerscythe"]={v=2000000,d=10,name="Silver Gingerscythe"},
["knife|silverhallows"]={v=50000000,d=10,name="Silver Hallows"},
["knife|silvericebreaker"]={v=35000000,d=10,name="Silver Icebreaker"},
["knife|silvericecrusher"]={v=1000000,d=10,name="Silver Icecrusher"},
["knife|silverlogchopper"]={v=35000000,d=10,name="Silver LogChopper"},
["knife|silverswirlyaxe"]={v=25000000,d=10,name="Silver Swirly Axe"},
["knife|silvertravelersaxe"]={v=1000000,d=10,name="Silver Travelers Axe"},
["knife|silvervampiresaxe"]={v=500000,d=10,name="Silver Vampires Axe"},
["knife|silvervampiresedge"]={v=2000000,d=10,name="Silver Vampires Edge"},
["knife|skulls"]={v=3,d=1.5,name="Skulls"},
["knife|skyline"]={v=1,d=0,name="Skyline Knife"},
["knife|slashed"]={v=1,d=2,name="Slashed"},
["knife|slasher"]={v=15,d=1,name="Slasher"},
["knife|slate"]={v=1,d=0,name="Slate"},
["knife|sleigh"]={v=1,d=2,name="Sleigh"},
["knife|slime"]={v=3,d=0.5,name="Slime Knife"},
["knife|snakebite"]={v=3,d=1,name="Snakebite Knife"},
["knife|snowfall"]={v=2,d=0,name="Snowfall"},
["knife|snowflake"]={v=55,d=3,name="Snowflake Knife"},
["knife|snowflakes"]={v=15,d=2,name="Snowflakes"},
["knife|snowglobe"]={v=2,d=2,name="Snowglobe Knife"},
["knife|snowman"]={v=2,d=2,name="Snowman Knife"},
["knife|snowy"]={v=1,d=2,name="Snowy"},
["knife|soda"]={v=1,d=2,name="Soda Knife"},
["knife|space"]={v=3,d=2,name="Space"},
["knife|sparkle9"]={v=30,d=2,name="Sparkle9"},
["knife|spectral"]={v=45,d=2,name="Spectral Knife"},
["knife|spectrum"]={v=3,d=2,name="Spectrum"},
["knife|spider"]={v=12,d=1,name="Spider"},
["knife|spirit"]={v=640,d=5,name="Spirit"},
["knife|splash"]={v=3,d=2,name="Splash"},
["knife|splatter"]={v=1,d=0,name="Splatter"},
["knife|spring"]={v=2,d=2,name="Spring Knife"},
["knife|squire"]={v=3,d=2,name="Squire"},
["knife|stainless"]={v=1,d=0,name="Stainless"},
["knife|stalker"]={v=3,d=0,name="Stalker"},
["knife|starfish"]={v=1,d=0,name="Starfish Knife"},
["knife|starry"]={v=2,d=2,name="Starry Knife"},
["knife|stars"]={v=2,d=2,name="Stars Knife"},
["knife|static"]={v=1,d=0,name="Static"},
["knife|stickers"]={v=3,d=0,name="Stickers Knife"},
["knife|stickersxmas"]={v=3,d=0,name="Stickers Xmas 2024"},
["knife|stockings"]={v=1,d=2,name="Stockings 2022"},
["knife|storm"]={v=2,d=1,name="Storm"},
["knife|strawberries"]={v=4,d=2,name="Strawberries Knife"},
["knife|striped"]={v=1,d=1.5,name="Striped Knife"},
["knife|sunrise"]={v=1100,d=4,name="Sunrise"},
["knife|sweater"]={v=75,d=2.5,name="Sweater Knife"},
["knife|sweet"]={v=150,d=2.5,name="Sweet"},
["knife|sweetheart"]={v=1,d=2,name="Sweetheart"},
["knife|swirl"]={v=17,d=2,name="Swirl Knife"},
["knife|swirlyaxe"]={v=40,d=2,name="SwirlyAxe"},
["knife|swirlyblade"]={v=13,d=1,name="Swirlyblade"},
["knife|tides"]={v=12,d=1,name="Tides"},
["knife|tnl"]={v=2,d=1,name="TNL"},
["knife|toxic"]={v=8,d=1.5,name="Toxic Knife"},
["knife|toy"]={v=2,d=2,name="Toy Knife"},
["knife|traveler"]={v=2,d=2.5,name="Traveler Knife"},
["knife|travelersaxe"]={v=8000,d=5,name="Travelers Axe"},
["knife|treats"]={v=1,d=3,name="Treats knife"},
["knife|tree"]={v=3,d=2,name="Tree Knife 23"},
["knife|tropical"]={v=3,d=2,name="Tropical Knife"},
["knife|turkey"]={v=2000,d=5,name="Turkey"},
["knife|turtle"]={v=3,d=0,name="Turtle Knife"},
["knife|ufos"]={v=3,d=3,name="UFOs Knife"},
["knife|valentine"]={v=1,d=2,name="Valentine"},
["knife|vampire"]={v=2,d=2,name="Vampire Knife"},
["knife|vampiresaxe"]={v=1650,d=5,name="Vampires Axe"},
["knife|vampiresedge"]={v=15,d=1,name="Vampires Edge"},
["knife|vines"]={v=2,d=2,name="Vines Knife"},
["knife|virtual"]={v=15,d=1,name="Virtual"},
["knife|void"]={v=15,d=2,name="Void"},
["knife|vortex"]={v=3,d=2,name="Vortex"},
["knife|wanwood"]={v=3,d=0,name="Wanwood"},
["knife|watcher"]={v=3,d=2,name="Watcher Knife"},
["knife|waves"]={v=275,d=4,name="Waves"},
["knife|wavy"]={v=3,d=0,name="Wavy Knife"},
["knife|web"]={v=1,d=1,name="Web"},
["knife|webs"]={v=3,d=1,name="Webs"},
["knife|whiteout"]={v=1,d=0,name="Whiteout"},
["knife|wintersedge"]={v=7,d=1,name="Winters Edge"},
["knife|witch"]={v=1,d=1,name="Witch"},
["knife|witchbrew"]={v=2,d=2,name="Witchbrew"},
["knife|witched"]={v=5,d=1.5,name="Witched"},
["knife|witchsbrew"]={v=5,d=0,name="Witchs Brew"},
["knife|wolf"]={v=4,d=1,name="Wolf"},
["knife|wood"]={v=1,d=0,name="Wood Knife"},
["knife|wraith"]={v=2,d=2,name="Wraith Knife"},
["knife|wraiths"]={v=3,d=2,name="Wraiths Knife"},
["knife|wrap"]={v=18,d=2,name="Wrap Knife"},
["knife|wrapped"]={v=3,d=2,name="Wrapped Knife 24"},
["knife|wreaths"]={v=3,d=2,name="Wreaths 2024"},
["knife|xeno"]={v=410,d=4.5,name="Xenoknife"},
["knife|xmas"]={v=10,d=1,name="Xmas"},
["knife|yellowseer"]={v=2,d=1,name="Yellow Seer"},
["knife|yummy"]={v=3,d=2,name="Yummy Knife"},
["knife|zombie"]={v=13,d=2,name="Zombie"},
["knife|zombified"]={v=125,d=3,name="Zombified Knife"},
},
built = "2026-10-02",
}
